/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as BusinessUsageRouteImport } from './routes/business.usage'
import { Route as BusinessSyntheticDataRouteImport } from './routes/business.synthetic-data'
import { Route as BusinessPricingRouteImport } from './routes/business.pricing'
import { Route as BusinessMarketingRouteImport } from './routes/business.marketing'
import { Route as ApiPublicTryAiRouteImport } from './routes/api/public/try-ai'
import { Route as ApiPublicApprovePaymentRouteImport } from './routes/api/public/approve-payment'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessUsageRoute = BusinessUsageRouteImport.update({
  id: '/business/usage',
  path: '/business/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSyntheticDataRoute = BusinessSyntheticDataRouteImport.update({
  id: '/business/synthetic-data',
  path: '/business/synthetic-data',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPricingRoute = BusinessPricingRouteImport.update({
  id: '/business/pricing',
  path: '/business/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessMarketingRoute = BusinessMarketingRouteImport.update({
  id: '/business/marketing',
  path: '/business/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTryAiRoute = ApiPublicTryAiRouteImport.update({
  id: '/api/public/try-ai',
  path: '/api/public/try-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApprovePaymentRoute = ApiPublicApprovePaymentRouteImport.update({
  id: '/api/public/approve-payment',
  path: '/api/public/approve-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/founder': typeof FounderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/pricing': typeof BusinessPricingRoute
  '/business/synthetic-data': typeof BusinessSyntheticDataRoute
  '/business/usage': typeof BusinessUsageRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/business/': typeof BusinessIndexRoute
  '/api/public/approve-payment': typeof ApiPublicApprovePaymentRoute
  '/api/public/try-ai': typeof ApiPublicTryAiRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/founder': typeof FounderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/pricing': typeof BusinessPricingRoute
  '/business/synthetic-data': typeof BusinessSyntheticDataRoute
  '/business/usage': typeof BusinessUsageRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/business': typeof BusinessIndexRoute
  '/api/public/approve-payment': typeof ApiPublicApprovePaymentRoute
  '/api/public/try-ai': typeof ApiPublicTryAiRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/founder': typeof FounderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/pricing': typeof BusinessPricingRoute
  '/business/synthetic-data': typeof BusinessSyntheticDataRoute
  '/business/usage': typeof BusinessUsageRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/business/': typeof BusinessIndexRoute
  '/api/public/approve-payment': typeof ApiPublicApprovePaymentRoute
  '/api/public/try-ai': typeof ApiPublicTryAiRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/founder'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/social'
    | '/terms'
    | '/welcome'
    | '/business/marketing'
    | '/business/pricing'
    | '/business/synthetic-data'
    | '/business/usage'
    | '/checkout/$planId'
    | '/checkout/success'
    | '/business/'
    | '/api/public/approve-payment'
    | '/api/public/try-ai'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/founder'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/social'
    | '/terms'
    | '/welcome'
    | '/business/marketing'
    | '/business/pricing'
    | '/business/synthetic-data'
    | '/business/usage'
    | '/checkout/$planId'
    | '/checkout/success'
    | '/business'
    | '/api/public/approve-payment'
    | '/api/public/try-ai'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/founder'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/social'
    | '/terms'
    | '/welcome'
    | '/business/marketing'
    | '/business/pricing'
    | '/business/synthetic-data'
    | '/business/usage'
    | '/checkout/$planId'
    | '/checkout/success'
    | '/business/'
    | '/api/public/approve-payment'
    | '/api/public/try-ai'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FounderRoute: typeof FounderRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  BusinessMarketingRoute: typeof BusinessMarketingRoute
  BusinessPricingRoute: typeof BusinessPricingRoute
  BusinessSyntheticDataRoute: typeof BusinessSyntheticDataRoute
  BusinessUsageRoute: typeof BusinessUsageRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  ApiPublicApprovePaymentRoute: typeof ApiPublicApprovePaymentRoute
  ApiPublicTryAiRoute: typeof ApiPublicTryAiRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/usage': {
      id: '/business/usage'
      path: '/business/usage'
      fullPath: '/business/usage'
      preLoaderRoute: typeof BusinessUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/synthetic-data': {
      id: '/business/synthetic-data'
      path: '/business/synthetic-data'
      fullPath: '/business/synthetic-data'
      preLoaderRoute: typeof BusinessSyntheticDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/pricing': {
      id: '/business/pricing'
      path: '/business/pricing'
      fullPath: '/business/pricing'
      preLoaderRoute: typeof BusinessPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/marketing': {
      id: '/business/marketing'
      path: '/business/marketing'
      fullPath: '/business/marketing'
      preLoaderRoute: typeof BusinessMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/try-ai': {
      id: '/api/public/try-ai'
      path: '/api/public/try-ai'
      fullPath: '/api/public/try-ai'
      preLoaderRoute: typeof ApiPublicTryAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approve-payment': {
      id: '/api/public/approve-payment'
      path: '/api/public/approve-payment'
      fullPath: '/api/public/approve-payment'
      preLoaderRoute: typeof ApiPublicApprovePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FounderRoute: FounderRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  BusinessMarketingRoute: BusinessMarketingRoute,
  BusinessPricingRoute: BusinessPricingRoute,
  BusinessSyntheticDataRoute: BusinessSyntheticDataRoute,
  BusinessUsageRoute: BusinessUsageRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  ApiPublicApprovePaymentRoute: ApiPublicApprovePaymentRoute,
  ApiPublicTryAiRoute: ApiPublicTryAiRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
