/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CodeRouteImport } from './routes/code'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalystRouteImport } from './routes/analyst'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as BusinessUsageRouteImport } from './routes/business.usage'
import { Route as BusinessSyntheticDataRouteImport } from './routes/business.synthetic-data'
import { Route as BusinessPricingRouteImport } from './routes/business.pricing'
import { Route as BusinessMarketingRouteImport } from './routes/business.marketing'
import { Route as ApiPublicTryAiRouteImport } from './routes/api/public/try-ai'
import { Route as ApiPublicApprovePaymentRouteImport } from './routes/api/public/approve-payment'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRoute = AnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessUsageRoute = BusinessUsageRouteImport.update({
  id: '/business/usage',
  path: '/business/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSyntheticDataRoute = BusinessSyntheticDataRouteImport.update({
  id: '/business/synthetic-data',
  path: '/business/synthetic-data',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPricingRoute = BusinessPricingRouteImport.update({
  id: '/business/pricing',
  path: '/business/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessMarketingRoute = BusinessMarketingRouteImport.update({
  id: '/business/marketing',
  path: '/business/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTryAiRoute = ApiPublicTryAiRouteImport.update({
  id: '/api/public/try-ai',
  path: '/api/public/try-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApprovePaymentRoute = ApiPublicApprovePaymentRouteImport.update({
  id: '/api/public/approve-payment',
  path: '/api/public/approve-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/analyst': typeof AnalystRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/code': typeof CodeRoute
  '/design': typeof DesignRoute
  '/docs': typeof DocsRouteWithChildren
  '/founder': typeof FounderRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/refund': typeof RefundRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/translate': typeof TranslateRoute
  '/voice': typeof VoiceRoute
  '/welcome': typeof WelcomeRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/pricing': typeof BusinessPricingRoute
  '/business/synthetic-data': typeof BusinessSyntheticDataRoute
  '/business/usage': typeof BusinessUsageRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/business/': typeof BusinessIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/approve-payment': typeof ApiPublicApprovePaymentRoute
  '/api/public/try-ai': typeof ApiPublicTryAiRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/analyst': typeof AnalystRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/code': typeof CodeRoute
  '/design': typeof DesignRoute
  '/founder': typeof FounderRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/refund': typeof RefundRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/translate': typeof TranslateRoute
  '/voice': typeof VoiceRoute
  '/welcome': typeof WelcomeRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/pricing': typeof BusinessPricingRoute
  '/business/synthetic-data': typeof BusinessSyntheticDataRoute
  '/business/usage': typeof BusinessUsageRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/business': typeof BusinessIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/public/approve-payment': typeof ApiPublicApprovePaymentRoute
  '/api/public/try-ai': typeof ApiPublicTryAiRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/analyst': typeof AnalystRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/code': typeof CodeRoute
  '/design': typeof DesignRoute
  '/docs': typeof DocsRouteWithChildren
  '/founder': typeof FounderRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/refund': typeof RefundRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/translate': typeof TranslateRoute
  '/voice': typeof VoiceRoute
  '/welcome': typeof WelcomeRoute
  '/business/marketing': typeof BusinessMarketingRoute
  '/business/pricing': typeof BusinessPricingRoute
  '/business/synthetic-data': typeof BusinessSyntheticDataRoute
  '/business/usage': typeof BusinessUsageRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/business/': typeof BusinessIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/approve-payment': typeof ApiPublicApprovePaymentRoute
  '/api/public/try-ai': typeof ApiPublicTryAiRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/analyst'
    | '/auth'
    | '/automations'
    | '/code'
    | '/design'
    | '/docs'
    | '/founder'
    | '/knowledge'
    | '/legal'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/refund'
    | '/seo'
    | '/sitemap.xml'
    | '/social'
    | '/support'
    | '/terms'
    | '/translate'
    | '/voice'
    | '/welcome'
    | '/business/marketing'
    | '/business/pricing'
    | '/business/synthetic-data'
    | '/business/usage'
    | '/checkout/$planId'
    | '/checkout/success'
    | '/docs/$slug'
    | '/business/'
    | '/docs/'
    | '/api/public/approve-payment'
    | '/api/public/try-ai'
    | '/api/public/razorpay/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/analyst'
    | '/auth'
    | '/automations'
    | '/code'
    | '/design'
    | '/founder'
    | '/knowledge'
    | '/legal'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/refund'
    | '/seo'
    | '/sitemap.xml'
    | '/social'
    | '/support'
    | '/terms'
    | '/translate'
    | '/voice'
    | '/welcome'
    | '/business/marketing'
    | '/business/pricing'
    | '/business/synthetic-data'
    | '/business/usage'
    | '/checkout/$planId'
    | '/checkout/success'
    | '/docs/$slug'
    | '/business'
    | '/docs'
    | '/api/public/approve-payment'
    | '/api/public/try-ai'
    | '/api/public/razorpay/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/analyst'
    | '/auth'
    | '/automations'
    | '/code'
    | '/design'
    | '/docs'
    | '/founder'
    | '/knowledge'
    | '/legal'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/refund'
    | '/seo'
    | '/sitemap.xml'
    | '/social'
    | '/support'
    | '/terms'
    | '/translate'
    | '/voice'
    | '/welcome'
    | '/business/marketing'
    | '/business/pricing'
    | '/business/synthetic-data'
    | '/business/usage'
    | '/checkout/$planId'
    | '/checkout/success'
    | '/docs/$slug'
    | '/business/'
    | '/docs/'
    | '/api/public/approve-payment'
    | '/api/public/try-ai'
    | '/api/public/razorpay/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  AnalystRoute: typeof AnalystRoute
  AuthRoute: typeof AuthRoute
  AutomationsRoute: typeof AutomationsRoute
  CodeRoute: typeof CodeRoute
  DesignRoute: typeof DesignRoute
  DocsRoute: typeof DocsRouteWithChildren
  FounderRoute: typeof FounderRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LegalRoute: typeof LegalRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  RefundRoute: typeof RefundRoute
  SeoRoute: typeof SeoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TranslateRoute: typeof TranslateRoute
  VoiceRoute: typeof VoiceRoute
  WelcomeRoute: typeof WelcomeRoute
  BusinessMarketingRoute: typeof BusinessMarketingRoute
  BusinessPricingRoute: typeof BusinessPricingRoute
  BusinessSyntheticDataRoute: typeof BusinessSyntheticDataRoute
  BusinessUsageRoute: typeof BusinessUsageRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  ApiPublicApprovePaymentRoute: typeof ApiPublicApprovePaymentRoute
  ApiPublicTryAiRoute: typeof ApiPublicTryAiRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/usage': {
      id: '/business/usage'
      path: '/business/usage'
      fullPath: '/business/usage'
      preLoaderRoute: typeof BusinessUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/synthetic-data': {
      id: '/business/synthetic-data'
      path: '/business/synthetic-data'
      fullPath: '/business/synthetic-data'
      preLoaderRoute: typeof BusinessSyntheticDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/pricing': {
      id: '/business/pricing'
      path: '/business/pricing'
      fullPath: '/business/pricing'
      preLoaderRoute: typeof BusinessPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/marketing': {
      id: '/business/marketing'
      path: '/business/marketing'
      fullPath: '/business/marketing'
      preLoaderRoute: typeof BusinessMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/try-ai': {
      id: '/api/public/try-ai'
      path: '/api/public/try-ai'
      fullPath: '/api/public/try-ai'
      preLoaderRoute: typeof ApiPublicTryAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approve-payment': {
      id: '/api/public/approve-payment'
      path: '/api/public/approve-payment'
      fullPath: '/api/public/approve-payment'
      preLoaderRoute: typeof ApiPublicApprovePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  AnalystRoute: AnalystRoute,
  AuthRoute: AuthRoute,
  AutomationsRoute: AutomationsRoute,
  CodeRoute: CodeRoute,
  DesignRoute: DesignRoute,
  DocsRoute: DocsRouteWithChildren,
  FounderRoute: FounderRoute,
  KnowledgeRoute: KnowledgeRoute,
  LegalRoute: LegalRoute,
  MarketplaceRoute: MarketplaceRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  RefundRoute: RefundRoute,
  SeoRoute: SeoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TranslateRoute: TranslateRoute,
  VoiceRoute: VoiceRoute,
  WelcomeRoute: WelcomeRoute,
  BusinessMarketingRoute: BusinessMarketingRoute,
  BusinessPricingRoute: BusinessPricingRoute,
  BusinessSyntheticDataRoute: BusinessSyntheticDataRoute,
  BusinessUsageRoute: BusinessUsageRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  ApiPublicApprovePaymentRoute: ApiPublicApprovePaymentRoute,
  ApiPublicTryAiRoute: ApiPublicTryAiRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
